databases:
  - name: ticketapp
    databaseName: ticketapp_791f
    user: ticketapp_791f_user

services:
  - type: web
    name: ticket_booking-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticketapp_791f
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false